### ISSUE TITLE
Setting docker-compose template and ENV variables

### ISSUE THREAD

**Issue by dalareo** [moritzfl/docker-fiduswriter#1]
Hi @moritzfl what about merging here (your repo) the two different approaches about dockerizing the app?

I think that using docker-compose with ENV variables gives more control about configuration and for me (I manage educaas.io project) is a must as long as I am looking for installation that require no modification of the code from the users.

Off-topic: BTW I am still not able to set ALLOWED_HOSTS properly and no working configuration is available, no matter if a set ['*'] or the proper domain. Any clue about this?

**Comment by dalareo** [comment]
I found out that configuration.py is not working for me, and environment variables are taken only from settings.py.

**Comment by moritzfl** [comment]
Sorry for my late response - I am in the middle of my exam phase atm :/

In general, I am open to the idea of merging here if the environment variables work correctly - just create PR if you want to merge.

I do have my latest build installed on my home server (Synology Diskstation/Linux) and for me it respects the settings in configuration.py (you may need to restart the container after performing changes to the file).

ALLOWED_HOSTS looks like this in my configuration.py:

~~~~
ALLOWED_HOSTS = [
    'localhost', 
    'some.url.net',
    '192.168.1.47',
] 
~~~~

**Comment by dalareo** [comment]
configuration.py not loading was because of a typo. It is solved now. I am using python:2.7 as base image, more simple. And I am also using root adding some modification at transpile.py. My Dockerfile:

```

FROM python:2.7

  MAINTAINER David A. Lareo <dalareo@gmail.com>
   
  EXPOSE 8000
   
  RUN apt-get update
  RUN apt-get install -y gettext npm nodejs nodejs-legacy
   
  RUN mkdir /code
  WORKDIR /code
  RUN mkdir static-libs
   
  VOLUME ["/code"]
   
  ADD requirements.txt /code/
  ADD postgresql-requirements.txt /code/
  ADD configuration.py-default /code/configuration.py
   
  RUN pip install -r requirements.txt
  RUN pip install -r postgresql-requirements.txt
   
  ADD . /code
   
  RUN ./manage.py init

```

**Comment by moritzfl** [comment]
closing this for now. We can reopen when tangible steps towards integration of environment variables and docker compose arte taken (which I don't personally plan to do atm).

**Comment by alfureu** [comment]
also would support this request
