### ISSUE TITLE
issues with init

### ISSUE THREAD

**Issue by johanneswilm** [moritzfl/docker-fiduswriter#8]
See the issue someone filed here: https://forum.fiduswriter.org/d/44-importerror-fot-start-manage-py-init-in-docker-latest

**Comment by moritzfl** [comment]
<img width="1438" alt="Bildschirmfoto 2019-10-13 um 09 01 35" src="https://user-images.githubusercontent.com/18644803/66712131-5d70db80-ed98-11e9-9040-1eabca5065e0.png">
Seems to be solved by using python3 - I will adjust the readme accordingly
